# -*- coding: utf-8 -*-
"""Assignment_3_Dolly Jha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDLNKA9Q_wsUrXYtrISJNGaM0Qs5Pbrz

#ASSIGNMENT 3:
Module 4: Functions & Modules in Python

##Task 1: Calculate Factorial Using a Function
Problem Statement: Write a Python program that:
1.   Defines a function named factorial that takes a number as an argument and calculates its factorial using a loop or recursion.
2.   Returns the calculated factorial.
3.   Calls the function with a sample number and prints the output.
"""

def fact(num):
   facto = 1
   if num == 1:
    return facto
   else:
    for i in range(1,num+1):
      facto = facto*i
    return facto
nu = int(input("Enter the number of which you want to find the factorial: "))
print(f"The Factorial of the number {nu} is {fact(nu)}")

"""#Task 2: Using the Math Module for Calculations

Problem Statement: Write a Python program that:
1.   Asks the user for a number as input.
2.   Uses the math module to calculate the:

    Square root of the number

    Natural logarithm (log base e) of the number

    Sine of the number (in radians)

3.   Displays the calculated results.

#
"""

import math
num = int(input("Enter a number: "))
print(f"The Square root of the number {num} is {math.sqrt(num)}")
print(f"The Natural log of the number {num} is {math.log(num)}")
print(f"The Sine of the number {num} is {math.sin(num)}")